/**
 * LightsOut — a deterministic Lights-Out puzzle minigame.
 *
 * Mechanics
 * ---------
 * - The grid starts in a scrambled state generated by reverse-engineering from
 *   the fully-solved (all-off) state, guaranteeing every puzzle is solvable.
 * - Clicking a cell toggles it **and** its orthogonal neighbours.
 * - Goal: turn all cells OFF.
 * - Player fails when they exhaust ``max_moves`` without solving the grid.
 *
 * Config (from `_pending_interaction.config`)
 * -------------------------------------------
 * difficulty.grid_size     — NxN grid (default 4)
 * difficulty.max_moves     — move budget (default 20)
 * difficulty.scramble_depth — scramble randomness (default 10)
 * assets.icon_on           — emoji/label for a lit cell  (default 💡)
 * assets.icon_off          — emoji/label for an unlit cell (default ⬛)
 */

import { useCallback, useEffect, useRef, useState } from "react";
import type { MinigameComponentProps } from "../registry";

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/** Build a flat all-off grid. */
function emptyGrid(size: number): boolean[] {
  return Array(size * size).fill(false);
}

/**
 * Toggle a cell and its four orthogonal neighbours in place.
 * Returns a **new** array (immutable update).
 */
function applyToggle(grid: boolean[], idx: number, size: number): boolean[] {
  const next = [...grid];
  const row = Math.floor(idx / size);
  const col = idx % size;
  const affected = [
    idx,
    row > 0 ? idx - size : -1,
    row < size - 1 ? idx + size : -1,
    col > 0 ? idx - 1 : -1,
    col < size - 1 ? idx + 1 : -1,
  ];
  for (const i of affected) {
    if (i >= 0) next[i] = !next[i];
  }
  return next;
}

/**
 * Reverse-engineer a solvable puzzle by starting from the solved state and
 * applying ``scrambleDepth`` random moves. Because every Lights-Out move is
 * its own inverse, the resulting state is always reachable.
 */
function generatePuzzle(size: number, scrambleDepth: number): boolean[] {
  let grid = emptyGrid(size);
  const total = size * size;
  for (let i = 0; i < scrambleDepth; i++) {
    const idx = Math.floor(Math.random() * total);
    grid = applyToggle(grid, idx, size);
  }
  // Edge-case: if scramble produces the solved state, force one toggle
  if (!grid.some(Boolean)) {
    grid = applyToggle(grid, 0, size);
  }
  return grid;
}

/** Count how many cells are still lit. */
function countLit(grid: boolean[]): number {
  return grid.filter(Boolean).length;
}

// ---------------------------------------------------------------------------
// Component
// ---------------------------------------------------------------------------

export default function LightsOut({ config, onComplete }: MinigameComponentProps) {
  const difficulty = (config.difficulty ?? {}) as Record<string, unknown>;
  const assets = (config.assets ?? {}) as Record<string, unknown>;
  const narrativeHooks = (config.narrative_hooks ?? {}) as Record<string, string>;

  const gridSize = typeof difficulty.grid_size === "number" ? difficulty.grid_size : 4;
  const maxMoves = typeof difficulty.max_moves === "number" ? difficulty.max_moves : 20;
  const scrambleDepth =
    typeof difficulty.scramble_depth === "number" ? difficulty.scramble_depth : 10;
  const iconOn = typeof assets.icon_on === "string" ? assets.icon_on : "💡";
  const iconOff = typeof assets.icon_off === "string" ? assets.icon_off : "⬛";

  const [grid, setGrid] = useState<boolean[]>(() => generatePuzzle(gridSize, scrambleDepth));
  const [movesMade, setMovesMade] = useState(0);
  const [finished, setFinished] = useState(false);
  const [triggeredHooks, setTriggeredHooks] = useState<string[]>([]);

  // Stable ref to onComplete so the effect below does not re-run on every render
  const onCompleteRef = useRef(onComplete);
  onCompleteRef.current = onComplete;

  // Derive counts
  const movesLeft = maxMoves - movesMade;
  const litCount = countLit(grid);
  const solved = litCount === 0;

  // Determine current narrative hook based on game state
  let currentHookText = "";
  if (solved && narrativeHooks["on_success"]) {
    currentHookText = narrativeHooks["on_success"];
  } else if (movesLeft <= 0 && movesMade > 0 && narrativeHooks["on_failure"]) {
    currentHookText = narrativeHooks["on_failure"];
  } else if (movesLeft === 1 && narrativeHooks["on_near_miss"]) {
    currentHookText = narrativeHooks["on_near_miss"];
  } else if (litCount <= 2 && narrativeHooks["on_near_miss"]) {
    currentHookText = narrativeHooks["on_near_miss"];
  }

  // Record triggered hooks during intermediate gameplay
  useEffect(() => {
    if (movesMade === 0) return;
    const triggered: string[] = [];
    if (movesLeft === 1 && narrativeHooks["on_near_miss"]) {
      triggered.push(narrativeHooks["on_near_miss"]);
    } else if (litCount > 0 && litCount <= 2 && narrativeHooks["on_near_miss"]) {
      triggered.push(narrativeHooks["on_near_miss"]);
    }
    if (triggered.length > 0) {
      setTriggeredHooks((prev) => {
        const next = [...prev];
        for (const hook of triggered) {
          if (!next.includes(hook)) {
            next.push(hook);
          }
        }
        return next;
      });
    }
  }, [movesLeft, litCount, movesMade, narrativeHooks]);

  // Check win/lose after each move and append final hooks
  useEffect(() => {
    if (finished) return;

    if (solved) {
      setFinished(true);
      if (narrativeHooks["on_success"]) {
        setTriggeredHooks((prev) => {
          const hook = narrativeHooks["on_success"];
          return prev.includes(hook) ? prev : [...prev, hook];
        });
      }
    } else if (movesLeft <= 0 && movesMade > 0) {
      setFinished(true);
      if (narrativeHooks["on_failure"]) {
        setTriggeredHooks((prev) => {
          const hook = narrativeHooks["on_failure"];
          return prev.includes(hook) ? prev : [...prev, hook];
        });
      }
    }
  }, [solved, movesLeft, movesMade, finished, narrativeHooks]);

  const handleCellClick = useCallback(
    (idx: number) => {
      if (finished) return;
      if (movesLeft <= 0) return;
      setGrid((prev) => applyToggle(prev, idx, gridSize));
      setMovesMade((prev) => prev + 1);
    },
    [finished, movesLeft, gridSize],
  );

  const handleAbort = useCallback(() => {
    if (finished) return;
    setFinished(true);
    onCompleteRef.current({
      status: "aborted",
      metrics: { moves_made: movesMade, moves_left: movesLeft, grid_remaining: litCount, perfect_run: false },
      minigame_specific_data: { moves_made: movesMade, grid_remaining: litCount },
      triggered_hooks: triggeredHooks,
    });
  }, [finished, movesMade, movesLeft, litCount, triggeredHooks]);

  return (
    <div className="lights-out-wrapper">
      <div className="lights-out-header">
        <span className="lights-out-stat">
          Moves left: <strong>{movesLeft}</strong>
        </span>
        <span className="lights-out-stat">
          Lit: <strong>{litCount}</strong>
        </span>
      </div>

      <div
        className="lights-out-grid"
        style={{ "--grid-size": gridSize } as React.CSSProperties}
      >
        {grid.map((lit, idx) => (
          <button
            key={idx}
            className={`lights-out-cell${lit ? " lights-out-cell--on" : " lights-out-cell--off"}`}
            onClick={() => handleCellClick(idx)}
            disabled={finished}
            aria-label={`Cell ${idx + 1}, ${lit ? "on" : "off"}`}
          >
            {lit ? iconOn : iconOff}
          </button>
        ))}
      </div>

      {currentHookText && (
        <div className="lights-out-narrative" style={{ marginBottom: '0.5rem', fontStyle: 'italic', color: 'var(--text-secondary)', textAlign: 'center' }}>
          {currentHookText}
        </div>
      )}

      {!finished && (
        <div className="lights-out-footer">
          <button className="btn btn-secondary btn-small" onClick={handleAbort}>
            Abandon puzzle
          </button>
        </div>
      )}

      {finished && solved && (
        <p className="lights-out-result lights-out-result--success">✅ Puzzle solved!</p>
      )}
      {finished && !solved && movesMade > 0 && movesLeft <= 0 && (
        <p className="lights-out-result lights-out-result--failure">❌ Out of moves!</p>
      )}

      {finished && (solved || (movesMade > 0 && movesLeft <= 0)) && (
        <div className="lights-out-footer" style={{ marginTop: '1rem' }}>
          <button
            className="btn btn-primary"
            onClick={() => {
              onComplete({
                status: solved ? "completed" : "failed",
                metrics: {
                  moves_made: movesMade,
                  moves_left: movesLeft,
                  grid_remaining: litCount,
                  perfect_run: solved && movesMade <= Math.ceil(scrambleDepth / 2),
                },
                minigame_specific_data: { moves_made: movesMade, grid_remaining: litCount },
                triggered_hooks: triggeredHooks,
              });
            }}
          >
            Close
          </button>
        </div>
      )}
    </div>
  );
}
